### ISSUE TITLE
Where can I learn more about Bitumen distributed NAS?

### ISSUE THREAD

**Issue by johnnyutahh** [fulldump/inceptiondb#8]
Where can I learn more about Bitumen distributed NAS (as per it being mentioned at https://github.com/fulldump/inceptiondb/blob/master/README.md)?

Initial web searches do not seem to show much besides asphalt-like references (for "bituman = aslphalt").

**Comment by johnnyutahh** [comment]
(bump -- thanks for any help)

**Comment by fulldump** [comment]
Hey @johnnyutahh, please let me know what are you looking for. As a summary:
* Bitumen is a distributed NAS designed to be fully funcional units (one machine) that can cooperate with other units to add redundancy and horizontal scalability. It is based on trust for availability. The project is on hold but it will resume soon.
* InceptionDB is a no-sql database service to store JSON documents that can be indexed for quick access. It has been simplified to the extreme by design so it persists on journal but operates in memory. Does not have scheduler (it saves some latency) so the indexed access is explicit, and parameters can vary depending on the kind of index used (for now key-value map and b-tree). Here you have a demo: https://inceptiondb.io/

Feel free to ask again for more information.
